server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: final-project
    version: 1.0.0
  profiles:
    active: dev   # dev, prod 선택 가능
  servlet:
    multipart:
      maxFileSize: 100MB # 파일 하나의 최대 크기
      maxRequestSize: 300MB  # 한 번에 최대 업로드 가능 용량
  main:
    allow-bean-definition-overriding: true

  # JPA
  jpa:
    hibernate:
      ddl-auto: validate
      # create, create-drop, update, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL8 기준
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        jdbc.time_zone: UTC
    open-in-view: false

#api
tmdb:
  api:
    base-url: https://api.themoviedb.org/3
    key: ${TMDB_API_KEY}

sportsdb:
  api:
    url: https://www.thesportsdb.com/api/v1/json
    key: ${SPORTSDB_API_KEY}

# security
security:
  jwt:
    issuer: "mopl-auth-server"
    secret: ${SECURITY_JWT_SECRET:change-me-jwt-secret-at-least-32chars}
    access-token-validity-seconds: ${SECURITY_JWT_ACCESS_TOKEN_VALIDITY_SECONDS:3600}
    refresh-token-validity-seconds: ${SECURITY_JWT_REFRESH_TOKEN_VALIDITY_SECONDS:1209600}
    header: "Authorization"
    prefix: "Bearer "
    algorithm: "HS256"
    clock-skew-seconds: 60
  oauth2:
    client:
      registration:
        google:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          scope:
            - email
            - profile


# S3
cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}